"""add customer_name to orders

Revision ID: 31eca2ec931f
Revises: b72435dde5b6
Create Date: 2026-06-04 22:22:27.991679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31eca2ec931f'
down_revision: Union[str, None] = 'b72435dde5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_name', sa.String(length=60), nullable=True))
    op.drop_index('idx_orders_created_at', table_name='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_orders_created_at', 'orders', ['created_at'], unique=False)
    op.drop_column('orders', 'customer_name')
    # ### end Alembic commands ###
